/// <reference types="Cypress" />

describe('Generate search and click', function() {

  it('runs a query and a click on normal behavior site ', () => {
    // Rupert shopping list
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('#loginWithGoogle').click()
    cy.get('.magic-box-input input', {timeout: 10000}).type('beans', {delay: 500})
    cy.get('.CoveoResultLink').contains("Heinz Baked Beans 415g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    //item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Doritos', {delay: 20})
    cy.get('.CoveoResultLink').contains("Doritos Chilli Heatwave Tortilla Chips 6x30g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Bread White', {delay: 20})
    cy.get('.CoveoResultLink').contains("Warburtons Soft Farmhouse Medium Sliced White Bread 800g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Tuna can', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Tuna Chunks Basics 160g (120g*)").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Oil Vegetable', {delay: 20})
    cy.get('.CoveoResultLink').contains("KTC Vegetable Oil 5L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Gel shower', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sanex Shower Gel 50ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Dog Food Large', {delay: 20})
    cy.get('.CoveoResultLink').contains("Pedigree Dentastix Daily Adult 1+ Large Dog Treats Dental Chews x56 Sticks").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Chicken nugget', {delay: 20})
    cy.get('.CoveoResultLink').contains("Birds Eye Chicken Nuggets x50 790g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine house', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's House Pinot Grigio Blush 2.25L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('cheese slice', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Red Leicester Cheese Slices 240g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // common items
    cy.get('.magic-box-input input', {timeout: 10000}).type('milk skim', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Skimmed Milk 2.27L (4 pint)").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('dark chocolate', {delay: 20})
    cy.get('.CoveoResultLink').contains("Lindt Excellence Chocolate Bar Dark Sea Salt 100g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('banana', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Fairtrade Bananas Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
      //cy.get('.magic-box-input input', {timeout: 10000}).type('broccoli', {delay: 20})
      //cy.get('.CoveoResultLink').contains("Sainsbury's Broccoli 335g").click()
      //cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('carrot', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Carrots Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('bleach', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Thin Bleach, Basics 2L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('lettuce', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Iceberg Lettuce 200g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('pineapple', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Large Pineapple").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('tissues', {delay: 20})
    cy.get('.CoveoResultLink').contains("Halo Moist Toilet Tissue x10 Wipes").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('chicken breast', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Roast Boneless Chicken Breasts x4 480g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine', {delay: 20})
    cy.get('.CoveoResultLink').contains("Campo Viejo Rioja Tempranillo 75cl").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    
    //Brent shopping list
    cy.get('.magic-box-input input', {timeout: 10000}).type('beans', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Stringless Beans 225g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    //item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('duck', {delay: 20})
    cy.get('.CoveoResultLink').contains("Clarence Court Duck Eggs x6").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Bread brown', {delay: 20})
    cy.get('.CoveoResultLink').contains("Warburtons Malted Grain & Seeds Medium Sliced Wholemeal Bread 400g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Tuna steak', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Tuna Steaks, Taste the Difference x2 240g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Oil Olive', {delay: 20})
    cy.get('.CoveoResultLink').contains("Napolina Extra Virgin Olive Oil 750ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Gel Soap', {delay: 20})
    cy.get('.CoveoResultLink').contains("Method Sweet Water Gel Handwash 354ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Dog Food Small', {delay: 20})
    cy.get('.CoveoResultLink').contains("Pooch & Mutt Small Dog Complete Mini Bites Chicken & Superfood Blend for Dogs 1kg").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Chicken whole', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Whole Chicken 1.2kg").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine sparkling', {delay: 20})
    cy.get('.CoveoResultLink').contains("Maschio Valdobbiadene Prosecco Docg 75cl").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('cheese soft', {delay: 20})
    cy.get('.CoveoResultLink').contains("Philadelphia Light Soft Cheese 180g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    // common items
    cy.get('.magic-box-input input', {timeout: 10000}).type('milk skim', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Skimmed Milk 2.27L (4 pint)").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('dark chocolate', {delay: 20})
    cy.get('.CoveoResultLink').contains("Lindt Excellence Chocolate Bar Dark Sea Salt 100g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('banana', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Fairtrade Bananas Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('broccoli', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Broccoli 335g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('carrot', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Carrots Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('bleach', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Thin Bleach, Basics 2L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('lettuce', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Iceberg Lettuce 200g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('pineapple', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's Large Pineapple").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('tissues', {delay: 20})
    cy.get('.CoveoResultLink').contains("Halo Moist Toilet Tissue x10 Wipes").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('chicken breast', {delay: 20})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Roast Boneless Chicken Breasts x4 480g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutype?csrf_token=b3cd0f70-bfb3-40e4-a366-d6942192dd8f#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine', {delay: 20})
    cy.get('.CoveoResultLink').contains("Campo Viejo Rioja Tempranillo 75cl").click()
})

  it('runs a query and a click on logging everything site ', () => {
    //Rupert shopping list
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('#loginWithGoogle').click()
    //First item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('beans', {delay: 100})
    cy.get('.CoveoResultLink').contains("Heinz Baked Beans 415g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    //item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Doritos', {delay: 100})
    cy.get('.CoveoResultLink').contains("Doritos Chilli Heatwave Tortilla Chips 6x30g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Bread White', {delay: 100})
    cy.get('.CoveoResultLink').contains("Warburtons Soft Farmhouse Medium Sliced White Bread 800g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
      //cy.get('.magic-box-input input', {timeout: 10000}).type('Tuna can', {delay: 100})
      //cy.get('.CoveoResultLink').contains("Sainsbury's Tuna Chunks Basics 160g (120g*)").click()
      //cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Oil Vegetable', {delay: 100})
    cy.get('.CoveoResultLink').contains("KTC Vegetable Oil 5L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Gel shower', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sanex Shower Gel 50ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Dog Food Large', {delay: 100})
    cy.get('.CoveoResultLink').contains("Pedigree Dentastix Daily Adult 1+ Large Dog Treats Dental Chews x56 Sticks").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Chicken nugget', {delay: 100})
    cy.get('.CoveoResultLink').contains("Birds Eye Chicken Nuggets x50 790g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine house', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's House Pinot Grigio Blush 2.25L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('cheese slice', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Red Leicester Cheese Slices 240g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // common items
    cy.get('.magic-box-input input', {timeout: 10000}).type('milk skim', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Skimmed Milk 2.27L (4 pint)").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('dark chocolate', {delay: 100})
    cy.get('.CoveoResultLink').contains("Lindt Excellence Chocolate Bar Dark Sea Salt 100g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('banana', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Fairtrade Bananas Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('broccoli', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Broccoli 335g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('carrot', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Carrots Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('bleach', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Thin Bleach, Basics 2L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('lettuce', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Iceberg Lettuce 200g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('pineapple', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Large Pineapple").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('tissues', {delay: 100})
    cy.get('.CoveoResultLink').contains("Halo Moist Toilet Tissue x10 Wipes").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('chicken breast', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Roast Boneless Chicken Breasts x4 480g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine', {delay: 100})
    cy.get('.CoveoResultLink').contains("Campo Viejo Rioja Tempranillo 75cl").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    
    //Brent shopping list
    cy.get('.magic-box-input input', {timeout: 10000}).type('beans', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Stringless Beans 225g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    //item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('duck', {delay: 100})
    cy.get('.CoveoResultLink').contains("Clarence Court Duck Eggs x6").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Bread brown', {delay: 100})
    cy.get('.CoveoResultLink').contains("Warburtons Malted Grain & Seeds Medium Sliced Wholemeal Bread 400g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Tuna steak', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Tuna Steaks, Taste the Difference x2 240g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Oil Olive', {delay: 100})
    cy.get('.CoveoResultLink').contains("Napolina Extra Virgin Olive Oil 750ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Gel Soap', {delay: 100})
    cy.get('.CoveoResultLink').contains("Method Sweet Water Gel Handwash 354ml").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Dog Food Small', {delay: 100})
    cy.get('.CoveoResultLink').contains("Pooch & Mutt Small Dog Complete Mini Bites Chicken & Superfood Blend for Dogs 1kg").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('Chicken whole', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Whole Chicken 1.2kg").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine sparkling', {delay: 100})
    cy.get('.CoveoResultLink').contains("Maschio Valdobbiadene Prosecco Docg 75cl").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // item search
    cy.get('.magic-box-input input', {timeout: 10000}).type('cheese soft', {delay: 100})
    cy.get('.CoveoResultLink').contains("Philadelphia Light Soft Cheese 180g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    // common items
    cy.get('.magic-box-input input', {timeout: 10000}).type('milk skim', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Skimmed Milk 2.27L (4 pint)").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('dark chocolate', {delay: 100})
    cy.get('.CoveoResultLink').contains("Lindt Excellence Chocolate Bar Dark Sea Salt 100g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('banana', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Fairtrade Bananas Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('broccoli', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Broccoli 335g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('carrot', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Carrots Loose").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('bleach', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Thin Bleach, Basics 2L").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('lettuce', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Iceberg Lettuce 200g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('pineapple', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's Large Pineapple").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('tissues', {delay: 100})
    cy.get('.CoveoResultLink').contains("Halo Moist Toilet Tissue x10 Wipes").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('chicken breast', {delay: 100})
    cy.get('.CoveoResultLink').contains("Sainsbury's British Roast Boneless Chicken Breasts x4 480g").click()
    cy.visit('https://search.cloud.coveo.com/pages/searchasyoutype0j90vzc7/searchasyoutypelogging?csrf_token=3f4222fe-7c16-4226-848a-1c53188bd0f8#sort=relevancy')
    cy.get('.magic-box-input input', {timeout: 10000}).type('wine', {delay: 100})
    cy.get('.CoveoResultLink').contains("Campo Viejo Rioja Tempranillo 75cl").click()
  })
})
